# Weather Dataset

In [ ]:
import pandas as pd

In [ ]:
data=pd.read_csv('/content/drive/MyDrive/csv/1. Weather Data.csv')

In [ ]:
data.head(2)

,Date/Time,Temp_C,Dew Point Temp_C,Rel Hum_%,Wind Speed_km/h,Visibility_km,Press_kPa,Weather
0,1/1/2012 0:00,-1.8,-3.9,86,4,8.0,101.24,Fog
1,1/1/2012 1:00,-1.8,-3.7,87,4,8.0,101.24,Fog

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8784 entries, 0 to 8783
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Date/Time         8784 non-null   object
 1   Temp_C            8784 non-null   float64
 2   Dew Point Temp_C  8784 non-null   float64
 3   Rel Hum_%         8784 non-null   int64
 4   Wind Speed_km/h   8784 non-null   int64
 5   Visibility_km     8784 non-null   float64
 6   Press_kPa         8784 non-null   float64
 7   Weather           8784 non-null   object
dtypes: float64(4), int64(2), object(2)
memory usage: 549.1+ KB

**Q. 1)  Find all the unique 'Wind Speed' values in the data.**

In [ ]:
data['Wind Speed_km/h'].unique()

array([ 4,  7,  6,  9, 15, 13, 20, 22, 19, 24, 30, 35, 39, 32, 33, 26, 44,
       43, 48, 37, 28, 17, 11,  0, 83, 70, 57, 46, 41, 52, 50, 63, 54,  2])

**Q. 2) Find the number of times when the 'Weather is exactly Clear'.**

**Q. 3) Find the number of times when the 'Wind Speed was exactly 4 km/h'.**

In [ ]:
data[data['Wind Speed_km/h']==4].count()

Date/Time           474
Temp_C              474
Dew Point Temp_C    474
Rel Hum_%           474
Wind Speed_km/h     474
Visibility_km       474
Press_kPa           474
Weather             474
dtype: int64

**Q. 4) Find out all the Null Values in the data.**

In [ ]:
data.isnull().sum()

Date/Time           0
Temp_C              0
Dew Point Temp_C    0
Rel Hum_%           0
Wind Speed_km/h     0
Visibility_km       0
Press_kPa           0
Weather             0
dtype: int64

**Q. 5) Rename the column name 'Weather' of the dataframe to 'Weather Condition'.**

In [ ]:
data.rename(columns={'Weather':'Weather cndition'})

,Date/Time,Temp_C,Dew Point Temp_C,Rel Hum_%,Wind Speed_km/h,Visibility_km,Press_kPa,Weather cndition
0,1/1/2012 0:00,-1.8,-3.9,86,4,8.0,101.24,Fog
1,1/1/2012 1:00,-1.8,-3.7,87,4,8.0,101.24,Fog
2,1/1/2012 2:00,-1.8,-3.4,89,7,4.0,101.26,"Freezing Drizzle,Fog"
3,1/1/2012 3:00,-1.5,-3.2,88,6,4.0,101.27,"Freezing Drizzle,Fog"
4,1/1/2012 4:00,-1.5,-3.3,88,7,4.8,101.23,Fog
...,...,...,...,...,...,...,...,...
8779,12/31/2012 19:00,0.1,-2.7,81,30,9.7,100.13,Snow
8780,12/31/2012 20:00,0.2,-2.4,83,24,9.7,100.03,Snow
8781,12/31/2012 21:00,-0.5,-1.5,93,28,4.8,99.95,Snow
8782,12/31/2012 22:00,-0.2,-1.8,89,28,9.7,99.91,Snow
8783,12/31/2012 23:00,0.0,-2.1,86,30,11.3,99.89,Snow

**Q. 6) What is the mean 'Visibility' ?**

In [ ]:
data.Visibility_km.mean()

27.664446721311478

**Q. 7) What is the Standard Deviation of 'Pressure'  in this data?**

In [ ]:
data.Press_kPa.std()

0.8440047459486483

**Q. 8) What is the Variance of 'Relative Humidity' in this data ?**

In [ ]:
data['Rel Hum_%'].var()

286.24855019850196

**Q. 9) Find all instances when 'Snow' was recorded.**

In [ ]:
data[data['Weather']=='Snow']

,Date/Time,Temp_C,Dew Point Temp_C,Rel Hum_%,Wind Speed_km/h,Visibility_km,Press_kPa,Weather
55,1/3/2012 7:00,-14.0,-19.5,63,19,25.0,100.95,Snow
84,1/4/2012 12:00,-13.7,-21.7,51,11,24.1,101.25,Snow
86,1/4/2012 14:00,-11.3,-19.0,53,7,19.3,100.97,Snow
87,1/4/2012 15:00,-10.2,-16.3,61,11,9.7,100.89,Snow
88,1/4/2012 16:00,-9.4,-15.5,61,13,19.3,100.79,Snow
...,...,...,...,...,...,...,...,...
8779,12/31/2012 19:00,0.1,-2.7,81,30,9.7,100.13,Snow
8780,12/31/2012 20:00,0.2,-2.4,83,24,9.7,100.03,Snow
8781,12/31/2012 21:00,-0.5,-1.5,93,28,4.8,99.95,Snow
8782,12/31/2012 22:00,-0.2,-1.8,89,28,9.7,99.91,Snow
8783,12/31/2012 23:00,0.0,-2.1,86,30,11.3,99.89,Snow

**Q. 10) Find all instances when 'Wind Speed is above 24' and 'Visibility is 25'.**

In [ ]:
data[(data['Wind Speed_km/h']>24) & (data['Visibility_km']==25)]

,Date/Time,Temp_C,Dew Point Temp_C,Rel Hum_%,Wind Speed_km/h,Visibility_km,Press_kPa,Weather
23,1/1/2012 23:00,5.3,2.0,79,30,25.0,99.31,Cloudy
24,1/2/2012 0:00,5.2,1.5,77,35,25.0,99.26,Rain Showers
25,1/2/2012 1:00,4.6,0.0,72,39,25.0,99.26,Cloudy
26,1/2/2012 2:00,3.9,-0.9,71,32,25.0,99.26,Mostly Cloudy
27,1/2/2012 3:00,3.7,-1.5,69,33,25.0,99.30,Mostly Cloudy
...,...,...,...,...,...,...,...,...
8705,12/28/2012 17:00,-8.6,-12.0,76,26,25.0,101.34,Mainly Clear
8753,12/30/2012 17:00,-12.1,-15.8,74,28,25.0,101.26,Mainly Clear
8755,12/30/2012 19:00,-13.4,-16.5,77,26,25.0,101.47,Mainly Clear
8759,12/30/2012 23:00,-12.1,-15.1,78,28,25.0,101.52,Mostly Cloudy
8760,12/31/2012 0:00,-11.1,-14.4,77,26,25.0,101.51,Cloudy

**Q. 11) What is the Mean value of each column against each 'Weather Condition ?**

In [ ]:
data.groupby('Weather').mean()

,Temp_C,Dew Point Temp_C,Rel Hum_%,Wind Speed_km/h,Visibility_km,Press_kPa
Weather,,,,,,
Clear,6.825716,0.089367,64.497738,10.557315,30.153243,101.587443
Cloudy,7.970544,2.375810,69.592593,16.127315,26.625752,100.911441
Drizzle,7.353659,5.504878,88.243902,16.097561,17.931707,100.435366
"Drizzle,Fog",8.067500,7.033750,93.275000,11.862500,5.257500,100.786625
"Drizzle,Ice Pellets,Fog",0.400000,-0.700000,92.000000,20.000000,4.000000,100.790000
"Drizzle,Snow",1.050000,0.150000,93.500000,14.000000,10.500000,100.890000
"Drizzle,Snow,Fog",0.693333,0.120000,95.866667,15.533333,5.513333,99.281333
Fog,4.303333,3.159333,92.286667,7.946667,6.248000,101.184067
Freezing Drizzle,-5.657143,-8.000000,83.571429,16.571429,9.200000,100.202857
"Freezing Drizzle,Fog",-2.533333,-4.183333,88.500000,17.000000,5.266667,100.441667
"Freezing Drizzle,Haze",-5.433333,-8.000000,82.000000,10.333333,2.666667,100.316667
"Freezing Drizzle,Snow",-5.109091,-7.072727,86.090909,16.272727,5.872727,100.520909
Freezing Fog,-7.575000,-9.250000,87.750000,4.750000,0.650000,102.320000
Freezing Rain,-3.885714,-6.078571,84.642857,19.214286,8.242857,99.647143
"Freezing Rain,Fog",-2.225000,-3.750000,89.500000,15.500000,7.550000,99.945000
"Freezing Rain,Haze",-4.900000,-7.450000,82.500000,7.500000,2.400000,100.375000
"Freezing Rain,Ice Pellets,Fog",-2.600000,-3.700000,92.000000,28.000000,8.000000,100.950000
"Freezing Rain,Snow Grains",-5.000000,-7.300000,84.000000,32.000000,4.800000,98.560000
Haze,-0.200000,-2.975000,81.625000,10.437500,7.831250,101.482500
Mainly Clear,12.558927,4.581671,60.667142,14.144824,34.264862,101.248832
"Moderate Rain,Fog",1.700000,0.800000,94.000000,17.000000,6.400000,99.980000
Moderate Snow,-5.525000,-7.250000,87.750000,33.750000,0.750000,100.275000
"Moderate Snow,Blowing Snow",-5.450000,-6.500000,92.500000,40.000000,0.600000,100.570000
Mostly Cloudy,10.574287,3.131174,62.102465,15.813920,31.253842,101.025288
Rain,9.786275,7.042810,83.624183,19.254902,18.856536,100.233333
Rain Showers,13.722340,9.187766,75.159574,17.132979,22.816489,100.404043
"Rain Showers,Fog",12.800000,12.100000,96.000000,13.000000,6.400000,99.830000
"Rain Showers,Snow Showers",2.150000,-1.500000,76.500000,22.500000,21.700000,101.100000
"Rain,Fog",8.273276,7.219828,93.189655,14.793103,6.873276,100.500862
"Rain,Haze",4.633333,2.066667,83.333333,11.666667,6.700000,100.540000
"Rain,Ice Pellets",0.600000,-0.600000,92.000000,24.000000,9.700000,100.120000
"Rain,Snow",1.055556,-0.566667,89.000000,28.388889,11.672222,99.951111
"Rain,Snow Grains",1.900000,-2.100000,75.000000,26.000000,25.000000,100.600000
"Rain,Snow,Fog",0.800000,0.300000,96.000000,9.000000,6.400000,100.730000
"Rain,Snow,Ice Pellets",1.100000,-0.175000,91.500000,23.250000,6.000000,100.105000
Snow,-4.524103,-7.623333,79.307692,20.038462,11.171795,100.536103
Snow Pellets,0.700000,-6.400000,59.000000,35.000000,2.400000,99.700000
Snow Showers,-3.506667,-7.866667,72.350000,19.233333,20.158333,100.963500
"Snow Showers,Fog",-10.675000,-11.900000,90.750000,13.750000,7.025000,101.292500
"Snow,Blowing Snow",-5.410526,-7.621053,84.473684,34.842105,4.105263,99.704737
"Snow,Fog",-5.075676,-6.364865,90.675676,17.324324,4.537838,100.688649
"Snow,Haze",-4.020000,-6.860000,80.600000,5.000000,4.640000,100.782000
"Snow,Ice Pellets",-1.883333,-3.666667,87.666667,23.833333,7.416667,100.548333
Thunderstorms,24.150000,19.750000,77.000000,7.500000,24.550000,100.230000
"Thunderstorms,Heavy Rain Showers",10.900000,9.000000,88.000000,9.000000,2.400000,100.260000
"Thunderstorms,Moderate Rain Showers,Fog",19.600000,18.500000,93.000000,15.000000,3.200000,100.010000
"Thunderstorms,Rain",20.433333,18.533333,89.000000,15.666667,19.833333,100.420000
"Thunderstorms,Rain Showers",20.037500,17.618750,86.375000,18.312500,15.893750,100.233750
"Thunderstorms,Rain Showers,Fog",21.600000,18.700000,84.000000,19.666667,9.700000,100.063333
"Thunderstorms,Rain,Fog",20.600000,18.600000,88.000000,19.000000,4.800000,100.080000

**Q. 12) What is the Minimum & Maximum value of each column against each 'Weather Condition ?**

In [ ]:
data.groupby('Weather').min().head(10)

,Date/Time,Temp_C,Dew Point Temp_C,Rel Hum_%,Wind Speed_km/h,Visibility_km,Press_kPa
Weather,,,,,,,
Clear,1/11/2012 1:00,-23.3,-28.5,20,0,11.3,99.52
Cloudy,1/1/2012 17:00,-21.4,-26.8,18,0,11.3,98.39
Drizzle,1/23/2012 21:00,1.1,-0.2,74,0,6.4,97.84
"Drizzle,Fog",1/23/2012 20:00,0.0,-1.6,85,0,1.0,98.65
"Drizzle,Ice Pellets,Fog",12/17/2012 9:00,0.4,-0.7,92,20,4.0,100.79
"Drizzle,Snow",12/17/2012 15:00,0.9,0.1,92,9,9.7,100.63
"Drizzle,Snow,Fog",12/18/2012 21:00,0.3,-0.1,92,7,2.4,97.79
Fog,1/1/2012 0:00,-16.0,-17.2,80,0,0.2,98.31
Freezing Drizzle,1/13/2012 10:00,-9.0,-12.2,78,6,4.8,98.44
"Freezing Drizzle,Fog",1/1/2012 2:00,-6.4,-9.0,82,6,3.6,98.74

In [ ]:
data.groupby('Weather').max().head(10)

,Date/Time,Temp_C,Dew Point Temp_C,Rel Hum_%,Wind Speed_km/h,Visibility_km,Press_kPa
Weather,,,,,,,
Clear,9/9/2012 5:00,32.8,20.4,99,33,48.3,103.63
Cloudy,9/9/2012 23:00,30.5,22.6,99,54,48.3,103.65
Drizzle,9/30/2012 3:00,18.8,17.7,96,30,25.0,101.56
"Drizzle,Fog",9/30/2012 2:00,19.9,19.1,100,28,9.7,102.07
"Drizzle,Ice Pellets,Fog",12/17/2012 9:00,0.4,-0.7,92,20,4.0,100.79
"Drizzle,Snow",12/19/2012 18:00,1.2,0.2,95,19,11.3,101.15
"Drizzle,Snow,Fog",12/22/2012 3:00,1.1,0.6,98,32,9.7,100.15
Fog,9/22/2012 0:00,20.8,19.6,100,22,9.7,103.04
Freezing Drizzle,2/1/2012 5:00,-2.3,-3.3,93,26,12.9,101.02
"Freezing Drizzle,Fog",12/10/2012 5:00,-0.3,-2.3,94,33,8.0,101.27

**Q. 13) Show all the Records where Weather Condition is Fog.**

In [ ]:
data[data['Weather']=='Fog']

,Date/Time,Temp_C,Dew Point Temp_C,Rel Hum_%,Wind Speed_km/h,Visibility_km,Press_kPa,Weather
0,1/1/2012 0:00,-1.8,-3.9,86,4,8.0,101.24,Fog
1,1/1/2012 1:00,-1.8,-3.7,87,4,8.0,101.24,Fog
4,1/1/2012 4:00,-1.5,-3.3,88,7,4.8,101.23,Fog
5,1/1/2012 5:00,-1.4,-3.3,87,9,6.4,101.27,Fog
6,1/1/2012 6:00,-1.5,-3.1,89,7,6.4,101.29,Fog
...,...,...,...,...,...,...,...,...
8716,12/29/2012 4:00,-16.0,-17.2,90,6,9.7,101.25,Fog
8717,12/29/2012 5:00,-14.8,-15.9,91,4,6.4,101.25,Fog
8718,12/29/2012 6:00,-13.8,-15.3,88,4,9.7,101.25,Fog
8719,12/29/2012 7:00,-14.8,-16.4,88,7,8.0,101.22,Fog
8722,12/29/2012 10:00,-12.0,-13.3,90,7,6.4,101.15,Fog

**Q. 14) Find all instances when 'Weather is Clear' or 'Visibility is above 40'.**

In [ ]:
data[(data['Weather']=='Clear') & (data['Visibility_km']>40)]

,Date/Time,Temp_C,Dew Point Temp_C,Rel Hum_%,Wind Speed_km/h,Visibility_km,Press_kPa,Weather
351,1/15/2012 15:00,-15.4,-22.8,53,24,48.3,102.71,Clear
352,1/15/2012 16:00,-15.1,-22.8,52,24,48.3,102.79,Clear
425,1/18/2012 17:00,-11.3,-18.8,54,26,48.3,101.54,Clear
440,1/19/2012 8:00,-13.7,-18.4,68,19,48.3,101.84,Clear
441,1/19/2012 9:00,-12.7,-17.2,69,17,48.3,101.73,Clear
...,...,...,...,...,...,...,...,...
8384,12/15/2012 8:00,-10.7,-15.6,67,13,48.3,102.69,Clear
8385,12/15/2012 9:00,-10.4,-15.9,64,19,48.3,102.74,Clear
8389,12/15/2012 13:00,-8.4,-14.7,60,19,48.3,102.64,Clear
8631,12/25/2012 15:00,-7.1,-13.7,59,17,48.3,101.98,Clear
8632,12/25/2012 16:00,-7.5,-13.9,60,11,48.3,102.03,Clear

**Q. 15) Find all instances when :
A. 'Weather is Clear' and 'Relative Humidity is greater than 50'**

In [ ]:
data[(data['Weather']=='Clear') & (data['Rel Hum_%']>50)]

,Date/Time,Temp_C,Dew Point Temp_C,Rel Hum_%,Wind Speed_km/h,Visibility_km,Press_kPa,Weather
114,1/5/2012 18:00,-7.1,-14.4,56,11,25.0,100.71,Clear
115,1/5/2012 19:00,-9.2,-15.4,61,7,25.0,100.80,Clear
116,1/5/2012 20:00,-9.8,-15.7,62,9,25.0,100.83,Clear
117,1/5/2012 21:00,-9.0,-14.8,63,13,25.0,100.83,Clear
241,1/11/2012 1:00,-10.7,-17.8,56,17,25.0,101.49,Clear
...,...,...,...,...,...,...,...,...
8646,12/26/2012 6:00,-13.4,-14.8,89,4,25.0,102.47,Clear
8698,12/28/2012 10:00,-6.1,-8.6,82,19,24.1,101.27,Clear
8713,12/29/2012 1:00,-11.9,-13.6,87,11,25.0,101.31,Clear
8714,12/29/2012 2:00,-11.8,-13.1,90,13,25.0,101.33,Clear
8756,12/30/2012 20:00,-13.8,-16.5,80,24,25.0,101.52,Clear

**B. 'Visibility is above 40'**

In [ ]:
data[(data['Weather']=='Clear') & (data['Visibility_km']>40)]

,Date/Time,Temp_C,Dew Point Temp_C,Rel Hum_%,Wind Speed_km/h,Visibility_km,Press_kPa,Weather
351,1/15/2012 15:00,-15.4,-22.8,53,24,48.3,102.71,Clear
352,1/15/2012 16:00,-15.1,-22.8,52,24,48.3,102.79,Clear
425,1/18/2012 17:00,-11.3,-18.8,54,26,48.3,101.54,Clear
440,1/19/2012 8:00,-13.7,-18.4,68,19,48.3,101.84,Clear
441,1/19/2012 9:00,-12.7,-17.2,69,17,48.3,101.73,Clear
...,...,...,...,...,...,...,...,...
8384,12/15/2012 8:00,-10.7,-15.6,67,13,48.3,102.69,Clear
8385,12/15/2012 9:00,-10.4,-15.9,64,19,48.3,102.74,Clear
8389,12/15/2012 13:00,-8.4,-14.7,60,19,48.3,102.64,Clear
8631,12/25/2012 15:00,-7.1,-13.7,59,17,48.3,101.98,Clear
8632,12/25/2012 16:00,-7.5,-13.9,60,11,48.3,102.03,Clear